name: Auto Merge PRs
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR automatically
        run: gh pr merge "$PR_URL" --squash --delete-branch --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
